parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Domain services
    Sales\:
        resource: '../../src/Sales/'
        exclude:
            - '../../src/Sales/Tests/'

    Billing\:
        resource: '../../src/Billing/'
        exclude:
            - '../../src/Billing/Tests/'

    Payments\:
        resource: '../../src/Payments/'
        exclude:
            - '../../src/Payments/Tests/'

    # Command and Query buses
    command.bus:
        class: Symfony\Component\Messenger\MessageBus
        arguments:
            - !tagged_iterator messenger.command_handler

    query.bus:
        class: Symfony\Component\Messenger\MessageBus
        arguments:
            - !tagged_iterator messenger.query_handler

    # Domain services
    Billing\Domain\Service\InvoiceNumberGenerator:
        class: Billing\Infrastructure\Service\SequentialInvoiceNumberGenerator

    Payments\Domain\Service\TransactionIdGenerator:
        class: Payments\Infrastructure\Service\UuidTransactionIdGenerator
