doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '15'

        types:
            uuid: 'Sales\Infrastructure\Doctrine\Type\UUIDType'
            email: 'Sales\Infrastructure\Doctrine\Type\EmailType'
            money: 'Sales\Infrastructure\Doctrine\Type\MoneyType'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Sales:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Sales/Infrastructure/Doctrine/Mapping'
                prefix: 'Sales\Domain\Model'
                alias: Sales
            Billing:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Billing/Infrastructure/Doctrine/Mapping'
                prefix: 'Billing\Domain\Model'
                alias: Billing
            Payments:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Payments/Infrastructure/Doctrine/Mapping'
                prefix: 'Payments\Domain\Model'
                alias: Payments
