nelmio_api_doc:
    documentation:
        info:
            title: DDD Monorepo API
            description: API for Sales, Billing, and Payments domains
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
